# Generated by Django 4.2.4 on 2023-08-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobyuser',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoesUser', to='troca_turno.operacao'),
        ),
    ]
