# Generated by Django 4.2.4 on 2023-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0002_alter_mobyuser_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagem',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
