# Generated by Django 4.2.4 on 2023-08-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0003_passagem_concluida'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mobyuser',
            managers=[
            ],
        ),
    ]
