# Generated by Django 4.2.4 on 2023-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0004_alter_mobyuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
    ]
