# Generated by Django 4.2.4 on 2023-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0005_alter_mobyuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='passagem',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
