# Generated by Django 4.2.4 on 2023-08-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0006_passagem_criado_em_passagem_finalizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passagem_receptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passagem_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
