# Generated by Django 4.2.4 on 2023-08-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0007_alter_passagem_receptor_alter_passagem_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passagem',
            name='anexo',
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('passagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='troca_turno.passagem')),
            ],
        ),
    ]
