# Generated by Django 4.2.4 on 2023-08-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0008_remove_passagem_anexo_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='passagem_torre', to='troca_turno.torre'),
        ),
    ]
