# Generated by Django 4.2.4 on 2023-08-22 11:31

from django.db import migrations, models
import django.db.models.deletion
import troca_turno.util.util


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0009_alter_passagem_torre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=troca_turno.util.util.Utils.attachment_file_path),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='passagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troca_turno.passagem'),
        ),
    ]
