# Generated by Django 4.1.10 on 2023-08-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0010_alter_anexo_arquivo_alter_anexo_passagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='passagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='troca_turno.passagem'),
        ),
    ]
