# Generated by Django 4.1.10 on 2023-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0011_alter_anexo_passagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DT',
            fields=[
                ('documento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tb_viagens',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='mobyuser',
            name='nome_atlas',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
    ]
