# Generated by Django 4.1.10 on 2023-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0012_dt_mobyuser_nome_atlas_delete_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('idPlanoViagem', models.CharField(max_length=50)),
                ('idVeiculo', models.CharField(max_length=100)),
                ('idCarreta', models.CharField(max_length=7)),
                ('transportador', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': '"public"."Viagens"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DT',
        ),
        migrations.AddField(
            model_name='passagem',
            name='dt_lista',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
