# Generated by Django 4.1.10 on 2023-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troca_turno', '0013_viagens_delete_dt_passagem_dt_lista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viagens',
        ),
        migrations.RemoveField(
            model_name='mobyuser',
            name='nome_atlas',
        ),
        migrations.AddField(
            model_name='mobyuser',
            name='gestor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
